[build]
languages = ["python"]

[phases.setup]
nixpkgs = [
  "libGL",
  "gcc",
  "ffmpeg",  # لو كنتي بتستخدمي الفيديو
  "python312Packages.pip"  # أهم حاجة تضيفي pip
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn app:app --host=0.0.0.0 --port=${PORT}"
