[build]
languages = ["python"]

[phases.setup]
nixpkgs = ["python312.withPackages (ps: with ps; [pip setuptools wheel opencv4])", "libGL", "ffmpeg", "gcc"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn app:app --host=0.0.0.0 --port=${PORT}"
