[build]
languages = ["python"]

[phases.setup]
nixpkgs = ["libGL", "gcc", "python312Full"]

[phases.install]
cmds = [
  "python3.12 -m ensurepip",
  "python3.12 -m pip install --upgrade pip",
  "python3.12 -m pip install -r requirements.txt"
]

[start]
cmd = "uvicorn app:app --host=0.0.0.0 --port=${PORT}"
